name: first_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ^3.8.1

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 
  get: ^4.7.2       # iOS-style icons
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  uuid: ^4.3.3                   # UUID generator
  google_fonts: ^6.3.0          # Custom Google Fonts support

# Dev dependencies for testing & linting
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0         # Recommended lint rules

# Flutter-specific configuration
flutter:

  # Include Material Icons font  
  uses-material-design: true

  # Declare asset folders or individual files
  assets:
    - assets/images/            # All files inside this folder will be available

  # Example for custom fonts (uncomment and edit to use)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700